
from .kraken2_taxa_table import Kraken2TaxaTableModule
from .kraken2_covid_fast_detect import Kraken2CovidFastDetectModule
from .kraken2_fast_taxa import FastKraken2TableModule
from .basic_stats_summary import BasicStatsTableModule
